# Generated by Django 3.1 on 2020-08-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='max_purchase_count',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='number_purchased',
        ),
        migrations.AddField(
            model_name='ticket',
            name='max_purchase_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='number_purchased',
            field=models.IntegerField(default=0),
        ),
    ]
