# Generated by Django 3.1 on 2020-08-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200808_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='max_purchase_count',
            field=models.IntegerField(),
        ),
    ]
