# Generated by Django 3.1 on 2020-08-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20200808_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
